version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g typescript
      - npm install --save @types/lodash
      - npm install @octokit/rest
      - npm install winston
      - npm install dotenv
      - npm i @types/jest
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - tsc
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - './dist/*'
    - './package.json'
    - './.env'
    - './node_modules'
  name: ForLambdaFunctionUse